### ISSUE TITLE
StableSwarmUI not detecting AMD GPU, ComfyUI backend can't initialize with AMD 6900XT because it's looking for cuda torch

### ISSUE THREAD

**Issue by LVT53** [Stability-AI/StableSwarmUI#217]
Hey there!

I've been trying to make StableSwarmUI work for several hours now and unfortunately it still doesn't work fully. I installed a fresh copy of Ubuntu 22.04.3 LTS. I then installed AMDGPU and with it ROCM 5.7.2 too, then the pytorch rocm nightly versions to pair. I also paid close attention that other torch,torchvision and torchaudio aren't installed besides the rocm versions before I ran any scripts.
I've successfully tested that pytorch is indeed using my gpu as the command ```python3 -c 'import torch; print(torch.cuda.is_available())'``` returns the string ```True```. I'm more sure that rocm works on my computer because I've used Automatic1111 a few days ago and it worked fast with my gpu included. 

SwarmUI's install went perfectly, supposedly as the terminal said and I saw no errors. It also launches without problems in a conda environment, except ComfyUI always exits unexpectedly because of some error. I think it's looking for an NVIDIA GPU (even SwarmUI says my gpu is "Unknown"). I've tried to manually install ComfyUI's dependencies, use args some launch args and also tried to include ```HSA_OVERRIDE_GFX_VERSION=10.3.0``` in launching ComfyUI with SwarmUI but I couldn't hack it.

Here's the full error code from my terminal:
```(sd) lvt53@Levi-Doyun-Linux:~/SSUI/StableSwarmUI$ ./launch-linux.sh
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  StableSwarmUI -> /home/lvt53/SSUI/StableSwarmUI/src/bin/live_release/StableSwarmUI.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.90
02:04:09.589 [Init] === StableSwarmUI v0.6.0.0 Starting ===
02:04:09.619 [Init] Prepping extension: StableSwarmUI.Builtin_StabilityAPIExtension.StabilityAPIExtension...
02:04:09.626 [Init] Prepping extension: StableSwarmUI.Builtin_ScorersExtension.ScorersExtension...
02:04:09.626 [Init] Prepping extension: StableSwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
02:04:09.626 [Init] Prepping extension: StableSwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
02:04:09.626 [Init] Prepping extension: StableSwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
02:04:09.626 [Init] Prepping extension: StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
02:04:09.627 [Init] Prepping extension: StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
02:04:09.650 [Init] Parsing command line...
02:04:09.650 [Init] Loading settings file...
02:04:09.660 [Init] Re-saving settings file...
02:04:09.670 [Init] Applying command line settings...
02:04:09.681 [Init] Prepping options...
02:04:09.749 [Init] Loading models list...
02:04:09.799 [Init] Loading backends...
02:04:09.800 [Init] Loading backends from file...
02:04:09.805 [Init] Prepping API...
02:04:09.806 [Init] Initializing backend #0 - ComfyUI Self-Starting...
02:04:09.806 [Init] Backend request handler loop ready...
02:04:09.807 [Init] Prepping webserver...
02:04:09.950 [Init] Scan for web extensions...
02:04:09.951 [Init] Readying extensions for launch...
02:04:09.951 [Init] Launching server...
02:04:09.951 [Init] Starting webserver on http://localhost:7801
02:04:09.975 [Init] Program is running.
02:04:10.161 [Info] Self-Start ComfyUI (Git Pull) exited properly.
Already up to date.
02:04:10.196 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
02:04:10.476 [Init] Launch web browser...
Gtk-Message: 02:04:10.655: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
02:04:11.047 [Error] [WebAPI] Error handling API request '/API/ListBackends': Request input has unknown session id
02:04:11.071 [Info] Creating new admin session for 127.0.0.1
02:04:11.085 [Info] Creating new admin session for 127.0.0.1
02:04:11.308 [Info] Self-Start ComfyUI-0 on port 7821 unexpectedly exited (if something failed, change setting `LogLevel` to `Debug` to see why!)
02:04:11.308 [Info] Self-Start ComfyUI-0 on port 7821 had errors before shutdown:
ComfyUI-0 on port 7821 error: Traceback (most recent call last):
ComfyUI-0 on port 7821 error:   File "/home/lvt53/SSUI/StableSwarmUI/dlbackend/ComfyUI/main.py", line 76, in <module>
ComfyUI-0 on port 7821 error:     import execution
ComfyUI-0 on port 7821 error:   File "/home/lvt53/SSUI/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 13, in <module>
ComfyUI-0 on port 7821 error:     import nodes
ComfyUI-0 on port 7821 error:   File "/home/lvt53/SSUI/StableSwarmUI/dlbackend/ComfyUI/nodes.py", line 20, in <module>
ComfyUI-0 on port 7821 error:     import comfy.diffusers_load
ComfyUI-0 on port 7821 error:   File "/home/lvt53/SSUI/StableSwarmUI/dlbackend/ComfyUI/comfy/diffusers_load.py", line 4, in <module>
ComfyUI-0 on port 7821 error:     import comfy.sd
ComfyUI-0 on port 7821 error:   File "/home/lvt53/SSUI/StableSwarmUI/dlbackend/ComfyUI/comfy/sd.py", line 5, in <module>
ComfyUI-0 on port 7821 error:     from comfy import model_management
ComfyUI-0 on port 7821 error:   File "/home/lvt53/SSUI/StableSwarmUI/dlbackend/ComfyUI/comfy/model_management.py", line 118, in <module>
ComfyUI-0 on port 7821 error:     total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
ComfyUI-0 on port 7821 error:   File "/home/lvt53/SSUI/StableSwarmUI/dlbackend/ComfyUI/comfy/model_management.py", line 87, in get_torch_device
ComfyUI-0 on port 7821 error:     return torch.device(torch.cuda.current_device())
ComfyUI-0 on port 7821 error:   File "/home/lvt53/SSUI/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 769, in current_device
ComfyUI-0 on port 7821 error:     _lazy_init()
ComfyUI-0 on port 7821 error:   File "/home/lvt53/SSUI/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
ComfyUI-0 on port 7821 error:     torch._C._cuda_init()
ComfyUI-0 on port 7821 error: RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx```

**Comment by mcmonkey4eva** [comment]
This relates to #23 - currently installation does not properly automatically handle AMD cards properly.

What you'll probably need to do (I don't have an AMD card so this is untested based on docs):

- close the swarm process
- Open a terminal to `StableSwarmUI/dlbackend/ComfyUI`
- `source venv/bin/activate`
- either:
    - `python3 -s -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.6`
- or:
    - `python3 -s -m pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.7`
- launch swarm and see if it works

The above based on https://github.com/comfyanonymous/ComfyUI#amd-gpus-linux-only

**Comment by LVT53** [comment]
Hey! Just wanted to thank you for pointing me in the right direction. I did what you wrote but it wasn't enough in itself. So I went back to the StableSwarmUI folder and check with pip list for what kind of torch is installed and it turned out I had cuda versions installed somehow when I especially paid attention to that not happening. So I uninstalled those 3, ran the rocm python install script again and it just magically loaded. Thank you again!

**Comment by azamet90** [comment]
> Hey! Just wanted to thank you for pointing me in the right direction. I did what you wrote but it wasn't enough in itself. So I went back to the StableSwarmUI folder and check with pip list for what kind of torch is installed and it turned out I had cuda versions installed somehow when I especially paid attention to that not happening. So I uninstalled those 3, ran the rocm python install script again and it just magically loaded. Thank you again!

i have same problem i think. can you help me how you did solve the problem?

**Comment by nix-wolf** [comment]
If your not careful while installing stuff and you miss á packages, like
transformers, I found if you install rocm pytorch vision and audio, then
after install transformers, it will reinstalled the cuda version. So I so
--only-if-needed, flag to píp and the. It will install the other deps.

**Comment by nix-wolf** [comment]
Also to note the reason why you install torch vision and audio together is
they need to be compiled for rocm together, where as transformers doesn't
care, accept it's likely in the deps list of the whl is wants torch-cu113
or something to that fashion. I do believe if you do not specify extra
arguments into píp in this case it will see rocm torch and think it needs
to install á different version and do it.
