### ISSUE TITLE
RuntimeError: CUDA error: operation not supported

### ISSUE THREAD

**Issue by YaseGar** [Stability-AI/StableSwarmUI#272]
Hi, I do have CUDA install and match the versions. I still can't get images after running 
I install cu121 first but it is not working, then I manually install the cu118 and ti still not working 

platform: Windows 10
CUDA Version: 11.8

[Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
 [Warning] ComfyUI-0 on port 7821 stderr: RuntimeError: CUDA error: operation not supported
[Info] No images were generated (all refused, or failed).

**Comment by mcmonkey4eva** [comment]
- Check debug logs for more info
- check that, uh, you have hardware capable of running SD? ie nvidia GPU with still-maintained firmware
- when in doubt if everything else seems to be right try a restart or a full reinstall

**Comment by YaseGar** [comment]
> * Check debug logs for more info
> * check that, uh, you have hardware capable of running SD? ie nvidia GPU with still-maintained firmware
> * when in doubt if everything else seems to be right try a restart or a full reinstall

Hi, thanks for reply. The logs is already on the top. I have two V100 installed.

**Comment by mcmonkey4eva** [comment]
What you posted isn't the _Debug_ log, it's the _Info_ log.

**Comment by allerias** [comment]
I was in the same case with 2 Tesla M60 cards.
I fixed the issue with this steps.
1- Go into the menu Server\Backends
2- Edit the running backend
3- add this in ExtraArgs: --disable-cuda-malloc

In my case with 8Gb NVRAM i need to add in ExtraArgs: --lowvram --force-fp16

additionnal informations: if you want to use in the same time multiple GPUs, you need to create additionnal Backends with the same ExtraArgs and just change the GPU_ID (must be 0, 1, 2, 3, ...)

Now i'm able to use the 2 GPUs of my two M60 graphics card for generate 4 images in the same time, one for each GPUs
